In [1]:
import pandas as pd
from sdv.tabular import CTGAN
import numpy as np
source_df  = pd.read_excel("Neospora.xls", true_values=["True"], false_values=["False"]);
source_df["EDAD"]  = pd.factorize(source_df['EDAD'])[0]
source_df["RAZA"]  = pd.factorize(source_df['RAZA'])[0]
source_df["NEOSPORA"]  = pd.factorize(source_df['NEOSPORA'])[0]
source_df["TORO"]  = pd.factorize(source_df['TORO'])[0]
source_df["INSEMINACION"]  = pd.factorize(source_df['INSEMINACION'])[0]
source_df["ABORTO"]  = pd.factorize(source_df['ABORTO'])[0]
source_df["REPETICION"]  = pd.factorize(source_df['REPETICION'])[0]
source_df["NO_CARGA"]  = pd.factorize(source_df['NO_CARGA'])[0]
source_df["DISTOCIAS"]  = pd.factorize(source_df['DISTOCIAS'])[0]
source_df["TERNEROS_DEBILES"]  = pd.factorize(source_df['TERNEROS_DEBILES'])[0]
source_df["MUERTE_EMBRIONARIA"]  = pd.factorize(source_df['MUERTE_EMBRIONARIA'])[0]

source_df.head()

,EDAD,RAZA,NEOSPORA,TORO,INSEMINACION,ABORTO,REPETICION,NO_CARGA,DISTOCIAS,TERNEROS_DEBILES,MUERTE_EMBRIONARIA
0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,1,0,1,1,1,0,0
2,0,2,1,0,0,0,1,1,1,0,0
3,0,2,1,0,1,1,0,1,0,1,0
4,0,1,0,0,1,1,0,0,1,0,0

In [2]:
model = CTGAN()
model.fit(source_df)

C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Pass n_components=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\mixture\_base.py:148: ConvergenceWarning: Number of distinct clusters (3) found smaller than n_clusters (10). Possibly due to duplicate points in X.
  random_state=random_state).fit(X).labels_
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Pass n_components=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\mixture\_base.py:148: ConvergenceWarning: Number of distinct clusters (4) found smaller than n_clusters (10). Possibly due to duplicate points in X.
  random_state=random_state).fit(X).labels_
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Pass n_components=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\mixture\_base.py:148: ConvergenceWarning: Number of distinct clusters (2) found smaller than n_clusters (10). Possibly due to duplicate points in X.
  random_state=random_state).fit(X).labels_
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Pass n_components=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\mixture\_base.py:148: ConvergenceWarning: Number of distinct clusters (2) found smaller than n_clusters (10). Possibly due to duplicate points in X.
  random_state=random_state).fit(X).labels_
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Pass n_components=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\mixture\_base.py:148: ConvergenceWarning: Number of distinct clusters (2) found smaller than n_clusters (10). Possibly due to duplicate points in X.
  random_state=random_state).fit(X).labels_
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Pass n_components=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\mixture\_base.py:148: ConvergenceWarning: Number of distinct clusters (2) found smaller than n_clusters (10). Possibly due to duplicate points in X.
  random_state=random_state).fit(X).labels_
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Pass n_components=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\mixture\_base.py:148: ConvergenceWarning: Number of distinct clusters (2) found smaller than n_clusters (10). Possibly due to duplicate points in X.
  random_state=random_state).fit(X).labels_
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Pass n_components=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\mixture\_base.py:148: ConvergenceWarning: Number of distinct clusters (2) found smaller than n_clusters (10). Possibly due to duplicate points in X.
  random_state=random_state).fit(X).labels_
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Pass n_components=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\mixture\_base.py:148: ConvergenceWarning: Number of distinct clusters (2) found smaller than n_clusters (10). Possibly due to duplicate points in X.
  random_state=random_state).fit(X).labels_
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Pass n_components=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\mixture\_base.py:148: ConvergenceWarning: Number of distinct clusters (2) found smaller than n_clusters (10). Possibly due to duplicate points in X.
  random_state=random_state).fit(X).labels_
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Pass n_components=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
C:\Users\jhon\.conda\envs\test 3\lib\site-packages\sklearn\mixture\_base.py:148: ConvergenceWarning: Number of distinct clusters (2) found smaller than n_clusters (10). Possibly due to duplicate points in X.
  random_state=random_state).fit(X).labels_

In [3]:
new_data = model.sample(10000)
new_data

,EDAD,RAZA,NEOSPORA,TORO,INSEMINACION,ABORTO,REPETICION,NO_CARGA,DISTOCIAS,TERNEROS_DEBILES,MUERTE_EMBRIONARIA
0,0,2,1,0,0,0,0,0,0,0,0
1,1,1,0,0,0,0,0,0,0,0,0
2,1,1,0,0,0,0,1,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,0
4,2,1,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,0,3,0,0,1,0,0,0,0,0,0
9996,1,2,0,0,1,0,1,0,0,0,0
9997,2,2,0,0,1,0,0,0,0,0,0
9998,0,0,1,0,0,0,0,0,0,0,0
9999,0,1,0,0,1,0,0,0,0,0,0

In [4]:
new_data.to_excel('Noeospora_extended.xls')