In [1]:
# importamos la libreria numpy de python
import numpy as np
#importamos la libreria pandas que nos permite crear modelos de datos
import pandas as pd
#importamos el clasificador rde random forest de la libreria sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier

#leemos el archivo dentro de un data frame de pandas
df = pd.read_excel("Neospora.xls", true_values=["True"], false_values=["False"]);
#visualizamos el archivo
df.head() # visualizamos las primerasfilas del dataframe

,EDAD,RAZA,NEOSPORA,TORO,INSEMINACION,ABORTO,REPETICION,NO_CARGA,DISTOCIAS,TERNEROS_DEBILES,MUERTE_EMBRIONARIA
0,> 3 AÑOS,AYR,False,True,False,False,True,False,True,False,False
1,> 3 AÑOS,HOL,False,True,True,False,False,True,False,False,False
2,> 3 AÑOS,NOR,True,True,False,False,False,True,False,False,False
3,> 3 AÑOS,NOR,True,True,True,True,True,True,True,True,False
4,> 3 AÑOS,HOL,False,True,True,True,True,False,False,False,False

In [2]:
# para verificar que el modelo funciona como tal, dividimos la informacion en dos grupos( para entrenamiento para pruebas) 
# agregando una columna adicionalque nos permitira separarlo m,as tarde

df["TRAINING_GROUP"] = np.random.uniform(0,1,len(df)) <= .80  
# usamos la libreria numpy para generar un numero  
# aleatorio y asignar el valor verdadero al 80 % de los datos
df["EDAD"]  = pd.factorize(df['EDAD'])[0]
df["RAZA"]  = pd.factorize(df['RAZA'])[0]

df.head()

# de esta forma tenemos separado de forma aleatoria el dataset entre los datos que usaremos para entrenamiento y los datos 
# que usaremos mas ademante para evaluar el resultado del modelo.

,EDAD,RAZA,NEOSPORA,TORO,INSEMINACION,ABORTO,REPETICION,NO_CARGA,DISTOCIAS,TERNEROS_DEBILES,MUERTE_EMBRIONARIA,TRAINING_GROUP
0,0,0,False,True,False,False,True,False,True,False,False,False
1,0,1,False,True,True,False,False,True,False,False,False,True
2,0,2,True,True,False,False,False,True,False,False,False,True
3,0,2,True,True,True,True,True,True,True,True,False,False
4,0,1,False,True,True,True,True,False,False,False,False,True

In [3]:
# separamos los datos de pruebas en grupos diferentes train y test

train, test = df[df['TRAINING_GROUP']==True], df[df['TRAINING_GROUP']==False]

print('Numero de observaciones para entrenamiento :',len(train))
print('Numero de observaciones para pruebas :',len(test))

train.head()

Numero de observaciones para entrenamiento : 789
Numero de observaciones para pruebas : 211

,EDAD,RAZA,NEOSPORA,TORO,INSEMINACION,ABORTO,REPETICION,NO_CARGA,DISTOCIAS,TERNEROS_DEBILES,MUERTE_EMBRIONARIA,TRAINING_GROUP
1,0,1,False,True,True,False,False,True,False,False,False,True
2,0,2,True,True,False,False,False,True,False,False,False,True
4,0,1,False,True,True,True,True,False,False,False,False,True
6,1,2,True,True,False,False,False,False,False,False,False,True
7,0,3,False,False,True,True,True,True,False,False,True,True

In [4]:
# Escojemos las features que el modelo debe de ultilizar (no de debe incluir el target NEOSPORA)

features = train.columns[0:11]
features = np.delete(features,[2])
print(features)

# factorizamos el target del conjunto de entrenamiento en valores que el modelo puede comprender

target_factorised = pd.factorize(train['NEOSPORA'])[0]
#print(target_factorised)

Index(['EDAD', 'RAZA', 'TORO', 'INSEMINACION', 'ABORTO', 'REPETICION',
       'NO_CARGA', 'DISTOCIAS', 'TERNEROS_DEBILES', 'MUERTE_EMBRIONARIA'],
      dtype='object')

In [5]:
clasifier = RandomForestClassifier(n_estimators=700)

# entrenamos el modelo con los features y el target factorizado para que el modelo lo entienda

clasifier.fit(train[features],target_factorised)

RandomForestClassifier(n_estimators=700)

In [6]:
# probamos que el modelo funciona e imprimimos los resutados que nos da
# resutlados predecidos
preds = clasifier.predict(test[features])
print(preds)

[1 1 1 1 0 0 0 1 0 1 0 1 0 0 0 1 1 0 1 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 1 0
 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 1 0 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0
 1 1 0 1 1 1 0 1 0 0 0 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0
 1 0 1 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1
 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0]

In [7]:
# imprimimos los datos originales del conjunto de datos de prueba
#resultados originales
test_factorised = pd.factorize(test['NEOSPORA'])[0]
print(test_factorised)

[0 1 1 1 1 0 0 0 0 1 0 1 0 1 1 1 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 1 1 0
 0 0 1 0 0 0 0 0 0 1 0 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 1 1 1 0 0 1 0 0 0 1 1
 1 0 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 0 0 0
 1 0 1 1 0 1 0 0 1 0 0 0 1 0 1 1 1 1 1 0 0 1 1 0 0 1 0 0 0 0 0 1 0 0 0 0 1
 1 0 1 0 1 1 0 1 0 1 0 0 0 0 1 1 0 0 1 1 1 0 1 1 1 0 0 1 1 1 0 0 0 0 0 1 0
 0 1 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1]

In [8]:
print(confusion_matrix(test_factorised,preds))
print(classification_report(test_factorised,preds))

[[73 38]
 [63 37]]
              precision    recall  f1-score   support

           0       0.54      0.66      0.59       111
           1       0.49      0.37      0.42       100

    accuracy                           0.52       211
   macro avg       0.52      0.51      0.51       211
weighted avg       0.52      0.52      0.51       211